### PR TITLE
Create Palindrome.cpp

### PR DESCRIPTION
**Pull request by Ishika0-0**

### CODE REVIEW

**Comment by Ishika0-0** [comment]
@extinctsion Can you please add the hacktoberfest accepted label

**Comment by extinctsion** [comment]
is it done?

**Comment by Ishika0-0** [comment]
> is it done?

Yes

**Comment by extinctsion** [comment]
Do u code in py?

**Comment by Ishika0-0** [comment]
> Do u code in py?

No c++

**Pull request merged**
